name: multiple-job

on:
  push:
    branches:
      - "*"

env:
  HISTORY_COMPONENT_NAME: ones-com
  REAL_COMPONENT_NAME: ${{ github.event.repository.name }}

  OWNER_IN_LOWER: bangwork

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create directory and files
        run: |
          mkdir ${{ github.workspace }}/myfolder
          echo "file1 contents" > ${{ github.workspace }}/myfolder/file1.txt
          echo "file2 contents" > ${{ github.workspace }}/myfolder/file2.txt
          mkdir ${{ github.workspace }}/myfolder/myfolder-child
          echo "file1 contents" > ${{ github.workspace }}/myfolder/myfolder-child/file1.txt
          echo "file2 contents" > ${{ github.workspace }}/myfolder/myfolder-child/file2.txt
      
      - name: Archive shared folder
        uses: actions/upload-artifact@v2
        with:
          name: myfolder
          path: myfolder



  job2:
    runs-on: ubuntu-latest
    steps: 
      - name: Download shared folder artifact
        uses: actions/download-artifact@v2
        with:
          name: myfolder
          path: myfolder

      - name: Use files from downloaded folder
      - name: Use files from directory
        run: |
          ls  myfolder
          cat myfolder/file1.txt
          cd myfolder/myfolder-child
          ls myfolder/myfolder-child