name: multiple-job

on:
  push:
    branches:
      - "*"

env:
  HISTORY_COMPONENT_NAME: ones-com
  REAL_COMPONENT_NAME: ${{ github.event.repository.name }}

  OWNER_IN_LOWER: bangwork

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create directory and files
        run: |
          mkdir myfolder
          echo "file1 contents" > myfolder/file1.txt
          echo "file2 contents" > myfolder/file2.txt
          mkdir myfolder/myfolder-child
          echo "file1 contents" > myfolder/myfolder-child/file1.txt
          echo "file2 contents" > myfolder/myfolder-child/file2.txt
      
      - name: Archive shared folder
        uses: actions/upload-artifact@v2
        with:
          name: myfolder
          path: myfolder

      - name: Archive script file
        uses: actions/upload-artifact@v2
        with:
          name: script
          path: myfolder/myfolder-child/file2.txt


  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps: 
      - name: Download shared folder artifact
        uses: actions/download-artifact@v3
        with:
          name: myfolder
          path: myfolder

      - name: Download shared file artifact
        uses: actions/download-artifact@v3
        with:
          name: script
          path: script

      - name: Use files from directory
        run: |
          ls
          ls  myfolder
          cat myfolder/file1.txt
          ls myfolder/myfolder-child