name: multiple-job

on:
  push:
    branches:
      - "*"

env:
  HISTORY_COMPONENT_NAME: ones-com
  REAL_COMPONENT_NAME: ${{ github.event.repository.name }}

  OWNER_IN_LOWER: bangwork

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create directory and files
        run: |
          mkdir ${{ github.workspace }}/myfolder
          echo "file1 contents" > ${{ github.workspace }}/myfolder/file1.txt
          echo "file2 contents" > ${{ github.workspace }}/myfolder/file2.txt
          mkdir ${{ github.workspace }}/myfolder/myfolder-child
          echo "file1 contents" > ${{ github.workspace }}/myfolder/myfolder-child/file1.txt
          echo "file2 contents" > ${{ github.workspace }}/myfolder/myfolder-child/file2.txt


  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Use files from directory
        run: |
          ls  ${{ github.workspace }}/myfolder
          cat ${{ github.workspace }}/myfolder/file1.txt
          cd ${{ github.workspace }}/myfolder/myfolder-child
          ls ${{ github.workspace }}/myfolder/myfolder-child